function env() {
  document.getElementById("demo").innerHTML = "•New York's population density has environmental pros and cons. It facilitates the highest mass transit use in the United States, but also concentrates pollution."+"<br>"+"<br>"+"• Gasoline consumption in the city is at the rate the national average was in the 1920s,[1] and greenhouse gas emissions are a fraction of the national average, at 7.1 metric tons per person per year, below San Francisco, at 11.2 metric tons, and the national average, at 24.5 metric tons."+"<br>"+"<br>"+"• New York City accounts for only 1% of United States greenhouse gas emissions while housing 2.7% of its population."+"<br>"+"<br>"+"• In September 2012, New York was named the #1 'America's Dirtiest City,' by a Travel+Leisure readership survey that rated the environmental quality of 35 prominent cities in the United States."+"<br>"+"<br>"+"<hr>"+"Work Cited"+"<br>"+"<br>"+"-“Environmental Issues in New York City.” Wikipedia, 13 Jan. 2021. Wikipedia, https://en.wikipedia.org/w/index.php?title=Environmental_issues_in_New_York_City&oldid=1000138302.";
}
function edu() {
  document.getElementById("demo").innerHTML = "• There are about 594,000 university students in New York City attending around 110 universities and colleges." + "<br>" + "<br>" + "• The New York City public school system is the largest in the United States. More than 1.1 million students are taught in more than 1,700 public schools with a budget of nearly $25 billion. The public school system is managed by the New York City Department of Education." + "<br>" + "<br>" + "• New York City has three public library systems, the New York Public Library, serving Manhattan, the Bronx, and Staten Island; the Brooklyn Public Library, serving Brooklyn; and the Queens Public Library, serving Queens." + "<hr>" + "WORKS CITED" + "<br>" + "<br>" + "https://en.wikipedia.org/wiki/Education_in_New_York_City";
}
function he() {
  document.getElementById("demo").innerHTML = "• On March 1st, 2020, scientists confirmed the first case of COVID-19 in NYC." + "<br>" + "• By early January 2021, there have been close to 26,000 deaths as a result of COVID-19 in NYC." + "<br>" + "• By January 13th 2021, there have also been around 438,544 confirmed cases of COVID-19 in NYC." + "<br>" + "<br>" + "<hr>" + "WORKS CITED" + "<br>" + "<br>" + "https://en.wikipedia.org/wiki/COVID-19_pandemic_in_New_York_City";
}
